// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itdbnbctsoeyojakxszs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZGJuYmN0c29leW9qYWt4c3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTA4OTcsImV4cCI6MjA2MTc2Njg5N30.uNiNJOX71VvtgkYp7dWab6-0sbSavEoEJG1vwK7Lys8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);